groups:
  - name: sportbet_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for {{ $labels.instance }}"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 1s for {{ $labels.instance }}"

      - alert: DatabaseConnectionHigh
        expr: mongodb_connections{state="current"} > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "Database connections are above 100 for {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 80% for {{ $labels.instance }}"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for {{ $labels.instance }}"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.instance }} service is down"

      - alert: DiskSpaceHigh
        expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage"
          description: "Disk usage is above 80% for {{ $labels.instance }}"

      - alert: FailedBets
        expr: increase(betting_failed_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of failed bets"
          description: "More than 10 bets failed in the last 5 minutes"

      - alert: WalletBalanceAnomaly
        expr: abs(increase(wallet_balance_change_total[1h])) > 10000
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Wallet balance anomaly detected"
          description: "Unusual wallet balance changes detected in the last hour"

      - alert: SecurityBreach
        expr: increase(security_violations_total[5m]) > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Security breach detected"
          description: "Multiple security violations detected in the last 5 minutes"
